"use client";
import { useParams } from "next/navigation";
import Link from "next/link";
import { races, athlete } from "../../../lib/mockData";
import { daysUntil, formatDate, getRaceTypeIcon } from "../../../lib/utils";

export default function RaceDetailPage() {
  const params = useParams();
  const race = races.find((r) => r.id === params.id);

  if (!race) {
    return (
      <div className="p-6">
        <p className="text-gray-400">Race not found.</p>
        <Link href="/races" className="text-brand-400 text-sm mt-2 inline-block">← Back to races</Link>
      </div>
    );
  }

  const days = daysUntil(race.date);
  const fitnessPercent = Math.min(100, Math.round((athlete.ctl / race.targetCTL) * 100));

  return (
    <div className="p-6 max-w-[1400px]">
      <Link href="/races" className="text-xs text-gray-500 hover:text-gray-300 mb-4 inline-block">← Back to Race Hub</Link>

      {/* Header */}
      <div className="flex items-start justify-between mb-6">
        <div className="flex items-center gap-4">
          <span className="text-4xl">{getRaceTypeIcon(race.type)}</span>
          <div>
            <h1 className="text-2xl font-bold text-white">{race.name}</h1>
            <p className="text-sm text-gray-500 mt-1">{race.location} · {formatDate(race.date)}</p>
          </div>
        </div>
        <div className="text-right">
          <div className="text-4xl font-bold text-white">{days}</div>
          <div className="text-xs text-gray-500">days to go</div>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-6">
        {/* Race Info */}
        <div className="col-span-4 space-y-4">
          <div className="bg-surface-850 border border-white/5 rounded-xl p-5">
            <h3 className="text-sm font-medium text-gray-300 mb-4">Race Info</h3>
            <div className="space-y-3">
              <div className="flex justify-between"><span className="text-xs text-gray-500">Distance</span><span className="text-sm text-white">{race.distance} km</span></div>
              <div className="flex justify-between"><span className="text-xs text-gray-500">Elevation</span><span className="text-sm text-white">{race.elevation}m D+</span></div>
              <div className="flex justify-between"><span className="text-xs text-gray-500">Priority</span><span className="text-sm text-white">{race.priority}-Race</span></div>
              <div className="flex justify-between"><span className="text-xs text-gray-500">Type</span><span className="text-sm text-white">{race.type === "road_run" ? "Road" : race.type === "trail" ? "Trail" : "Cycling"}</span></div>
            </div>
          </div>

          <div className="bg-surface-850 border border-white/5 rounded-xl p-5">
            <h3 className="text-sm font-medium text-gray-300 mb-4">Fitness Target</h3>
            <div className="flex items-end gap-2 mb-2">
              <span className="text-3xl font-bold text-white">{athlete.ctl}</span>
              <span className="text-gray-500 text-sm mb-1">/ {race.targetCTL} CTL</span>
            </div>
            <div className="w-full bg-gray-800 rounded-full h-2 mb-2">
              <div className={`h-2 rounded-full ${fitnessPercent >= 80 ? "bg-emerald-500" : "bg-amber-500"}`} style={{ width: `${fitnessPercent}%` }}></div>
            </div>
            <p className="text-xs text-gray-500">{fitnessPercent}% of target fitness</p>
          </div>
        </div>

        {/* Map + Pacer placeholder */}
        <div className="col-span-8 space-y-4">
          <div className="bg-surface-850 border border-white/5 rounded-xl p-6 h-64 flex items-center justify-center">
            <div className="text-center">
              <div className="text-gray-500 text-sm mb-2">Interactive Race Map</div>
              <div className="text-gray-600 text-xs">Upload GPX file in Settings to render the course map and elevation profile</div>
            </div>
          </div>

          <div className="bg-surface-850 border border-white/5 rounded-xl p-6">
            <h3 className="text-sm font-medium text-gray-300 mb-4">Race Predictor & Pacer</h3>
            <div className="text-center py-8">
              <div className="text-gray-500 text-sm">Predicted finish time and pacing strategy</div>
              <div className="text-gray-600 text-xs mt-1">Will be generated by Claude based on your current fitness and course profile</div>
              <button className="mt-4 px-4 py-2 bg-brand-600/20 text-brand-400 text-sm rounded-lg border border-brand-500/30 hover:bg-brand-600/30">
                📋 Generate Race Plan → Copy to Claude
              </button>
            </div>
          </div>

          <div className="bg-surface-850 border border-white/5 rounded-xl p-6">
            <h3 className="text-sm font-medium text-gray-300 mb-4">Race-Day Fuelling Timeline</h3>
            <div className="text-center py-6">
              <div className="text-gray-500 text-sm">Gel, hydration & nutrition schedule</div>
              <div className="text-gray-600 text-xs mt-1">Will be generated based on race distance, duration, and your Nduranz products</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
