export const athlete = {
  name: "Alexandre Santos",
  age: 29,
  weight: 76.2,
  targetWeight: 71,
  bodyFat: 22,
  targetBodyFat: 15,
  ftp: 181,
  thresholdPace: { min: "5:07", max: "5:28" },
  maxHR: 188,
  restingHR: 59,
  ctl: 42,
  atl: 38,
  tsb: 4,
};

export const races = [
  {
    id: "aveiro-2026",
    name: "Europe Marathon Aveiro — Half Marathon",
    shortName: "Aveiro HM",
    date: "2026-04-26",
    type: "road_run",
    distance: 21.1,
    elevation: 93,
    priority: "A",
    targetCTL: 55,
    location: "Aveiro, Portugal",
    status: "upcoming",
  },
  {
    id: "nexebra-2026",
    name: "Trilhos da Nexebra Trail — Mini-Trail",
    shortName: "Nexebra Trail",
    date: "2026-05-10",
    type: "trail",
    distance: 14,
    elevation: 470,
    priority: "B",
    targetCTL: 52,
    location: "Chão de Couce, Ansião",
    status: "upcoming",
  },
  {
    id: "serra-estrela-2026",
    name: "Granfondo Serra da Estrela — Mediofondo",
    shortName: "Serra da Estrela",
    date: "2026-06-28",
    type: "cycling",
    distance: 97,
    elevation: 2700,
    priority: "B",
    targetCTL: 58,
    location: "Manteigas, Serra da Estrela",
    status: "upcoming",
  },
  {
    id: "lisbon-2026",
    name: "Hyundai Half Marathon Lisbon",
    shortName: "Lisbon HM",
    date: "2026-10-11",
    type: "road_run",
    distance: 21.1,
    elevation: 50,
    priority: "A",
    targetCTL: 60,
    location: "Lisbon, Portugal",
    status: "upcoming",
  },
];

export const mockWeek = [
  { day: "Mon", date: "2026-03-02", workout: { type: "easy_run", name: "Easy Run", duration: 45, tss: 35, zone: "Z2", icon: "run" }, workDensity: "medium", energy: 4, completed: true },
  { day: "Tue", date: "2026-03-03", workout: { type: "gym_a", name: "Gym A — Legs", duration: 60, tss: 40, zone: "STR", icon: "gym" }, workDensity: "heavy", energy: 3, completed: true },
  { day: "Wed", date: "2026-03-04", workout: { type: "intervals", name: "Bike Intervals", duration: 60, tss: 65, zone: "Z4-Z5", icon: "bike" }, workDensity: "medium", energy: 3, completed: false, isToday: true },
  { day: "Thu", date: "2026-03-05", workout: { type: "tempo_run", name: "Tempo Run", duration: 50, tss: 55, zone: "Z3-Z4", icon: "run" }, workDensity: "light", energy: null, completed: false },
  { day: "Fri", date: "2026-03-06", workout: { type: "gym_d", name: "Gym D — Legs", duration: 60, tss: 40, zone: "STR", icon: "gym" }, workDensity: "light", energy: null, completed: false },
  { day: "Sat", date: "2026-03-07", workout: { type: "long_run", name: "Long Run", duration: 90, tss: 95, zone: "Z2", icon: "run" }, workDensity: "rest", energy: null, completed: false },
  { day: "Sun", date: "2026-03-08", workout: { type: "easy_ride", name: "Recovery Ride", duration: 60, tss: 30, zone: "Z1", icon: "bike" }, workDensity: "rest", energy: null, completed: false },
];

export const burnoutScore = { total: 42, training: 48, work: 45, sleep: 30, hrHrv: 35, trend: "stable", level: "moderate" };
export const weeklyTSS = { planned: 360, actual: 140, percentage: 39 };
