"use client";
import { useState } from "react";

const supplements = [
  { name: "Creatine (Nduranz)", time: "Post-workout", checked: false },
  { name: "Electrolytes", time: "During training", checked: false },
  { name: "Caffeine", time: "Pre-race / hard sessions only", checked: false },
];

const todaySession = {
  type: "Bike Intervals",
  duration: "60 min",
  intensity: "Z4-Z5",
  pre: { what: "Nduranz Nrgy Unit Drink (90g carbs) + banana", when: "2h before" },
  during: { what: "Nduranz Gel (45g carbs) at 30min", when: "During session" },
  post: { what: "Nduranz Recovery mix + meal within 1h", when: "Within 30 min" },
};

export default function FuellingPage() {
  const [checks, setChecks] = useState(supplements.map(() => false));

  const toggleCheck = (i) => {
    const updated = [...checks];
    updated[i] = !updated[i];
    setChecks(updated);
  };

  return (
    <div className="p-6 max-w-[1400px]">
      <h1 className="text-2xl font-bold text-white mb-2">Fuelling & Nutrition</h1>
      <p className="text-sm text-gray-500 mb-6">Session fuelling, race nutrition & supplements</p>

      <div className="grid grid-cols-12 gap-6">
        {/* Today's fuelling */}
        <div className="col-span-7">
          <div className="bg-surface-850 border border-white/5 rounded-xl p-6">
            <h2 className="text-sm font-medium text-gray-300 mb-1">Today's Session Fuelling</h2>
            <p className="text-xs text-gray-500 mb-4">{todaySession.type} · {todaySession.duration} · {todaySession.intensity}</p>

            <div className="space-y-4">
              {[
                { label: "PRE", emoji: "🍌", ...todaySession.pre },
                { label: "DURING", emoji: "⚡", ...todaySession.during },
                { label: "POST", emoji: "🥤", ...todaySession.post },
              ].map((item) => (
                <div key={item.label} className="flex items-start gap-3 p-3 bg-surface-900 rounded-lg">
                  <span className="text-lg">{item.emoji}</span>
                  <div>
                    <div className="text-[10px] font-bold text-gray-500 mb-0.5">{item.label} · {item.when}</div>
                    <div className="text-sm text-gray-200">{item.what}</div>
                  </div>
                </div>
              ))}
            </div>

            <p className="text-[10px] text-gray-600 mt-4 italic">Fuelling recommendations will be auto-generated by Gemini based on session type and intensity</p>
          </div>
        </div>

        {/* Supplements */}
        <div className="col-span-5">
          <div className="bg-surface-850 border border-white/5 rounded-xl p-6">
            <h2 className="text-sm font-medium text-gray-300 mb-4">Daily Supplement Checklist</h2>
            <div className="space-y-3">
              {supplements.map((supp, i) => (
                <label key={supp.name} className="flex items-center gap-3 cursor-pointer p-2 rounded-lg hover:bg-white/5">
                  <input
                    type="checkbox"
                    checked={checks[i]}
                    onChange={() => toggleCheck(i)}
                    className="w-4 h-4 rounded border-gray-600 bg-gray-800 text-brand-500 focus:ring-brand-500"
                  />
                  <div>
                    <div className={`text-sm ${checks[i] ? "text-gray-400 line-through" : "text-gray-200"}`}>{supp.name}</div>
                    <div className="text-[10px] text-gray-500">{supp.time}</div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          <div className="bg-surface-850 border border-white/5 rounded-xl p-6 mt-4">
            <h2 className="text-sm font-medium text-gray-300 mb-4">Race Fuelling Plans</h2>
            <div className="text-center py-4">
              <p className="text-xs text-gray-500">Race-specific fuelling timelines will appear here when generated</p>
              <button className="mt-3 px-3 py-1.5 bg-brand-600/20 text-brand-400 text-xs rounded-lg border border-brand-500/30">
                📋 Generate Plan → Copy to Claude
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
